# Generated by Django 3.1.4 on 2020-12-16 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='access_key',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='data',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='data', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
